# 项目相关配置
pistachio:
  name: Pistachio
  version: 0.0.1
  copyrightYear: 2023

# minio 配置
minio:
  endpoint: http://123.57.48.127:9000
  accessKey: admin
  secretKey: admin123456
  bucketName: mlcloud

# 开发环境配置
server:
  port: 18004
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: null
    lettuce:
      pool:
        min-idle: 10
        max-idle: 30
        max-active: 8
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pistachio-db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    hikari:
      max-lifetime: 3600000

snowflake:
  # 设置机器id
  worker-id: 1
  datacenter-id: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '系统管理模块'
      paths-to-match: '/**'
      packages-to-scan: 'com.pistachio.admin.controller.system'
    - group: "上传模块"
      paths-to-match: "/**"
      packages-to-scan: "com.pistachio.admin.controller.upload"
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  basic:
    enable: false
    username: xiaofeng
    password: 123456
