# Spring配置
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

# token配置
sa-token:
  token-name: pistachioToken
  #有效期(秒)
  timeout: 2592000
  #最低活跃频率(秒);超过这个值就会被冻结,-1表示不限制
  active-timeout: -1
  # 是否允许统一账号多地同时登录
  is-concurrent: true
  # 多人登录统一账号时,是否共用一个token
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 令牌自定义标识
  token-prefix: Authorization
  # 公钥
  public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+aYWIbEglCcCNXXk2wJsfmefpjImYQgXRZ9pueAVfE823mfO6UTJQlUy1BEaHSuV2Gq/PzoGcBVGf0RAZnHx6pFNpGljlWL7WWMQ1SOoF84ztxBjXWbJPbmxgDsyfR5xz3xoSAILvWPRpG51tnRDW5HsuqNIdDUryUQf9gYSHDQIDAQAB
  # 私钥
  private-key: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAL5phYhsSCUJwI1deTbAmx+Z5+mMiZhCBdFn2m54BV8TzbeZ87pRMlCVTLUERodK5XYar8/OgZwFUZ/REBmcfHqkU2kaWOVYvtZYxDVI6gXzjO3EGNdZsk9ubGAOzJ9HnHPfGhIAgu9Y9GkbnW2dENbkey6o0h0NSvJRB/2BhIcNAgMBAAECgYEAmwtpQ/CHvkD2nSVjsgWbSlwTzsQ0tdnsytp5rkHkfcquU7X0E95RzfQEBdF5bGi79zM7vUY1m0lpcWzWY0RcxkhQ2arDCY3SQrEGX1rMnbBHzgJFLT92jcHtjUYE3jgbAJnzoz169JIpdX+ZZhnCviPBy1N8E5jFHjuPnCa0izECQQDn/oPQgXy1a7JXnB+Udcbwq243kK1Xj9vrBMEHQLajZFx24Fmxz6FVCCFDLTxliCKSeKVf61NWNZfyK974lr3nAkEA0h2BvOoPFDbfch3ul5gR0SLJjQP5PwC/4hE3lXU1AkcOMR0VlGJbGMpzvqdQYkOHVFUDzNkDwfq0TlRNGGus6wJBAM40v904+ywWifKtZrSC601IUzM4eZr217bSBvD3aF9a+YUAbTlLIE+AZnBbaO+mTXR7oCLd/LkH8gLjU9EJy8kCQQCRCr1cY1Y1ZgupAvCIxPjHnXP0XCHaU/IhZDEygs4s3E/3p1QWMi8gVeDAY08iBeuNU4JkDgqCBUYiLB9sFCgxAkBpq2KX1kuYlEq/repr0EIpVjI/KSHJ/wq2CiGv3utHUd7pvWIfxcFT6cKDsVqM7xwEwzgCJOa5Z7zffX7Attcp

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*


# 日志配置
logging:
  level:
    com.pistachio: debug
    org.springframework: info
